version: '3.0'

services:
  nginx:
    image: nginx:stable
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro

  php:
    image: figured/php-dev:7.2
    working_dir: /var/www/html
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html:cached
      - ./storage:/var/www/html/storage
      - ./docker/volumes/php/composer:/root/.composer:cached

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./docker/volumes/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: figured
      MYSQL_USER: figured
      MYSQL_PASSWORD: secret
